spring.application.name=healthcare

spring.datasource.url=postgresql://postgres:FbBanJQqudvUuanhANWvxPHOitVZHFBV@postgres-tolu.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=FbBanJQqudvUuanhANWvxPHOitVZHFBV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

